{
  boolean caught=false;
  try {
    foo.invoke(instance,args);
  }
 catch (  InvocationTargetException ex) {
    caught=exceptionClass.isInstance(ex.getTargetException());
  }
  assertTrue(caught);
}
