{
  loadText("fun foo() { throw new Exception(); }");
  final Method main=generateFunction();
  boolean caught=false;
  try {
    main.invoke(null);
  }
 catch (  InvocationTargetException e) {
    if (e.getTargetException().getClass() == Exception.class) {
      caught=true;
    }
  }
  assertTrue(caught);
}
